import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  architectureSidebar: [{type: 'autogenerated', dirName: 'architecture'}],
  apiReferenceSidebar: [{type: 'autogenerated', dirName: 'api-reference'}],
  moreSidebar: [{type: 'autogenerated', dirName: 'more'}],
};

export default sidebars;
