//! Path-based migration auto-discovery.
//!
//! Scans the crate's `migrations/` directory at build time and generates the
//! module declarations plus an ordered `all()` registry into `OUT_DIR`, which
//! `migrations/mod.rs` pulls in with `include!`. Modelled on Alembic's "read
//! every file in the versions/ directory" discovery: dropping a new
//! `mXXXX_*.rs` file into `migrations/` registers it automatically — no manual
//! `mod` line and no hand-maintained list.
//!
//! Identity is the migration's own `version()` (never the filename); the
//! migrator sorts by it at runtime, so this file only needs to *discover* the
//! migrations, not order them. Each file must contain exactly one
//! `impl Migration for <Struct>` — the struct name is read from that line.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let migrations_dir = Path::new(&manifest_dir).join("migrations");

    // Re-run when a migration file is added, removed, or edited. The directory
    // line catches add/remove (its mtime changes); the per-file lines catch
    // edits to existing migrations.
    println!("cargo:rerun-if-changed={}", migrations_dir.display());

    let mut files = migration_files(&migrations_dir);
    files.sort();

    let mut module_decls = String::new();
    let mut registry_entries = String::new();
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let module = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("migration file stem");
        let struct_name = struct_name(path);
        module_decls.push_str(&format!(
            "#[path = {path:?}]\nmod {module};\n",
            path = path.to_string_lossy(),
        ));
        registry_entries.push_str(&format!("        Box::new({module}::{struct_name}),\n"));
    }

    let generated = format!(
        "// @generated by build.rs — do not edit. One entry per migrations/mXXXX_*.rs file.\n\
         {module_decls}\n\
         /// Every discovered migration. The migrator sorts these by `version()`.\n\
         pub fn all() -> Vec<Box<dyn Migration>> {{\n    vec![\n{registry_entries}    ]\n}}\n"
    );
    fs::write(
        Path::new(&out_dir).join("migrations_generated.rs"),
        generated,
    )
    .expect("write generated migration registry");
}

/// The `mXXXX_*.rs` files in the migrations directory (excludes `mod.rs`).
fn migration_files(dir: &Path) -> Vec<PathBuf> {
    fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read migrations dir {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| {
            path.extension().is_some_and(|ext| ext == "rs")
                && path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .is_some_and(|stem| stem.starts_with('m') && stem != "mod")
        })
        .collect()
}

/// Read the struct name from the file's `impl Migration for <Struct>` line.
fn struct_name(path: &Path) -> String {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read migration {}: {e}", path.display()));
    const MARKER: &str = "impl Migration for ";
    let start = content.find(MARKER).unwrap_or_else(|| {
        panic!(
            "migration {} has no `impl Migration for <Struct>`",
            path.display()
        )
    }) + MARKER.len();
    let name: String = content[start..]
        .chars()
        .take_while(|c| c.is_alphanumeric() || *c == '_')
        .collect();
    assert!(
        !name.is_empty(),
        "migration {} has a malformed `impl Migration for` line",
        path.display()
    );
    name
}
