name: Actionlint

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Run actionlint
        uses: raven-actions/actionlint@v2
        with:
          matcher: true
